version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
    container_name: wegift-gateway-eval
    # container_name: wegift-gateway
    ports:
      - "4000:4000"
    restart: unless-stopped
    env_file:
      - ./gateway/.env.eval
    # env_file:
    #   - ./gateway/.env
    environment:
      - NODE_ENV=docker
    depends_on:
      - auth-service
      - user-service
      - wishlist-service
      - exchange-service

  auth-service:
    build:
      context: ./services/auth-service
    container_name: wegift-auth-service-eval
    # container_name: wegift-auth-service
    ports:
      - "3001:3001"
    restart: unless-stopped
    env_file:
      - ./services/auth-service/.env.eval
    # env_file:
    #   - ./services/auth-service/.env
    environment:
      - NODE_ENV=docker
    depends_on:
      - mysql

  user-service:
    build:
      context: ./services/user-service
    container_name: wegift-user-service-eval
    # container_name: wegift-user-service
    ports:
      - "3003:3003"
    restart: unless-stopped
    env_file:
      - ./services/user-service/.env.eval
    # env_file:
    #   - ./services/user-service/.env
    environment:
      - NODE_ENV=docker
    volumes:
      - ./services/user-service/public/uploads:/app/public/uploads
    depends_on:
      - mysql

  wishlist-service:
    build:
      context: ./services/wishlist-service
    container_name: wegift-wishlist-service-eval
    # container_name: wegift-wishlist-service
    ports:
      - "3004:3004"
    restart: unless-stopped
    env_file:
      - ./services/wishlist-service/.env.eval
    # env_file:
    #   - ./services/wishlist-service/.env
    environment:
      - NODE_ENV=docker
    depends_on:
      - mysql

  exchange-service:
    build:
      context: ./services/exchange-service
    container_name: wegift-exchange-service-eval
    # container_name: wegift-exchange-service
    ports:
      - "3002:3002"
    restart: unless-stopped
    env_file:
      - ./services/exchange-service/.env.eval
    # env_file:
    #   - ./services/exchange-service/.env
    environment:
      - NODE_ENV=docker
    depends_on:
      - mysql

  mysql:
      image: mysql:8.0
      container_name: wegift-mysql-eval
      environment:
        MYSQL_ROOT_PASSWORD: root_password_eval
        MYSQL_DATABASE: wegift_eval
        MYSQL_USER: user_eval
        MYSQL_PASSWORD: password_eval
      ports:
        - "3307:3306"
      volumes:
        - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      restart: unless-stopped
