version: '3.8'

services:
  gateway:
    env_file:
      - ./gateway/.env.eval
    environment:
      - NODE_ENV=eval

  auth-service:
    env_file:
      - ./services/auth-service/.env.eval
    environment:
      - NODE_ENV=eval

  user-service:
    env_file:
      - ./services/user-service/.env.eval
    environment:
      - NODE_ENV=eval

  wishlist-service:
    env_file:
      - ./services/wishlist-service/.env.eval
    environment:
      - NODE_ENV=eval

  exchange-service:
    env_file:
      - ./services/exchange-service/.env.eval
    environment:
      - NODE_ENV=eval

  mysql:
    image: mysql:8.0
    container_name: wegift-mysql-eval
    environment:
      MYSQL_ROOT_PASSWORD: root_password_eval
      MYSQL_DATABASE: wegift_eval
      MYSQL_USER: user_eval
      MYSQL_PASSWORD: password_eval
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
