const config = {
  AUTH_SERVICE: process.env.AUTH_SERVICE!,
  EXCHANGE_SERVICE: process.env.EXCHANGE_SERVICE!,
  USER_SERVICE: process.env.USER_SERVICE!,
  WISHLIST_SERVICE: process.env.WISHLIST_SERVICE!,
  NOTIFICATION_SERVICE: process.env.NOTIFICATION_SERVICE!,
  FRONTEND_SERVICE: process.env.FRONTEND_SERVICE!,
};

export default config;
